### ISSUE TITLE
Issues with 5mm magnets

### ISSUE THREAD

**Issue by scrouthtv** [riskable/void_switch#12]
Hello,

I tried creating some switches with 5mm magnets. 
The wall around the magnet in the stem seems to be too small:
![image](https://user-images.githubusercontent.com/23227405/156316035-0406dd89-ec8f-4e43-afbe-4b611630b267.png)

Indeed, when I put the magnet in, one of the walls simply snapped off. 

Is there any way to increase the wall size at this position?

Thanks in advance :)

**Comment by riskable** [comment]
If you plan to use magnets larger than 4mm you'll need to adjust the `STEM_DIAMETER` so that the walls surrounding the magnet don't bulge out like in your screenshot.  You may also need to make some adjustments here and there in other places but I'm not 100% certain. It's been a long time since I messed with different magnet sizes.
